build:
  cuda_version: "12.8"
  python_version: "3.12"
  system_packages:
    - "git"
  python_packages:
    - "huggingface_hub"
  run:
    - "git clone https://github.com/nianxi666/HunyuanImage-3.0 && cd HunyuanImage-3.0 && pip install torch==2.7.1 torchvision==0.22.1 torchaudio==2.7.1 --index-url https://download.pytorch.org/whl/cu128 && hf download tencent/HunyuanImage-3.0 --local-dir ./HunyuanImage-3"
